### ISSUE TITLE
Crashes on some other hardware 

### ISSUE THREAD

**Issue by ibabushkin** [ibabushkin/gabelstaplerwm#38]
The following crash can be triggered when pressing the brightness keys on some systems:
```
INFO:gabelstaplerwm::wm::window_system: executing binding for KeyPress { code: 233, mods: 0, mode: Normal }
thread 'main' panicked at 'wait() should either return Ok or panic', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/process/process_unix.rs:74
stack backtrace:
   1:     0x5559793389ba - std::sys::imp::backtrace::tracing::imp::write::h1d59ca58eb86a1e2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x555979337d01 - std::panicking::default_hook::{{closure}}::hc8550e2dc230bf9b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x55597933720c - std::panicking::rust_panic_with_hook::h319375f6b98710b0
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:367
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   4:     0x555979336a51 - std::panicking::begin_panic::h8462d4bdb88c73cc
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
   5:     0x55597933f847 - std::process::Command::spawn::h174a0ef6a697e968
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/process/process_unix.rs:74
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/process.rs:559
   6:     0x5559792e8044 - gabelstaplerwm::wm::config::exec_command::h3ed28e821b936b9b
   7:     0x5559792fe4f1 - gabelstaplerwm::wm::config::setup_wm::{{closure}}::hb4bda0dcbc2dc40b
   8:     0x5559792f470f - gabelstaplerwm::main::h403f0e00ab78e9c3
   9:     0x5559793005ef - main
  10:     0x7f44d98354e0 - __libc_start_main
  11:     0x5559792dad79 - _start
  12:                0x0 - <unknown>
```

**Comment by ibabushkin** [comment]
This is due to some code outside of the master branch. The spawn functionality should be reworked there.
